export enum ControlledErrorType {
    REQUEST = 'REQUEST',
    BACKEND_SYSTEM = 'BACKEND_SYSTEM',
    FRONTEND_SYSTEM = 'FRONTEND_SYSTEM',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    UNKNOWN = 'UNKNOWN'
}
