export enum INDUSTRIES {
  STUDENT = 'STUDENT',
  WORKER = 'WORKER',
  ENTREPRENEUR = 'ENTREPRENEUR',
  FREELANCER = 'FREELANCER',
  ARTIST = 'ARTIST',
  PROGRAMMER = 'PROGRAMMER',
  DESIGNER = 'DESIGNER',
  MARKETER = 'MARKETER',
  ADMINISTRATOR = 'ADMINISTRATOR',
  WRITER = 'WRITER',
  OTHER = 'OTHER'
}

export const INDUSTRIES_LIST = [
    INDUSTRIES.STUDENT,
    INDUSTRIES.WORKER,
    INDUSTRIES.ENTREPRENEUR,
    INDUSTRIES.FREELANCER,
    INDUSTRIES.ARTIST,
    INDUSTRIES.PROGRAMMER,
    INDUSTRIES.DESIGNER,
    INDUSTRIES.MARKETER,
    INDUSTRIES.ADMINISTRATOR,
    INDUSTRIES.WRITER,
    INDUSTRIES.OTHER
];