export enum PLACE_NOISE_LEVEL {
    VERY_QUIET = "VERY_QUIET",
    QUITE = "QUITE",
    MODERATE = "MODERATE",
    LOUD = "LOUD",
    VERY_LOUD = "VERY_LOUD",
}

export const placeNoiseLevelOptions = [
    PLACE_NOISE_LEVEL.VERY_QUIET,
    PLACE_NOISE_LEVEL.QUITE,
    PLACE_NOISE_LEVEL.MODERATE,
    PLACE_NOISE_LEVEL.LOUD,
    PLACE_NOISE_LEVEL.VERY_LOUD,
]