export enum PLACE_RULES {
  OPEN_AT = "OPEN_AT",
  CLOSED_AT = "CLOSED_AT",
  PET_FRIENDLY = "PET_FRIENDLY",
  SMOKING = "SMOKING",
  UNDER_AGE = "UNDER_AGE",
  TIME_LIMIT = "TIME_LIMIT",
}

export enum PLACE_TIME_LIMIT_RULE {
  NO_LIMIT = "NO_LIMIT",
  UNLIMITED = "UNLIMITED",
  PER_HOUR = "PER_HOUR",
}

export enum NOISE_POLICY_RULE_ENUM {
  QUIET_ONLY = "QUIET_ONLY",
  MODERATE_NOISE_ALLOWED = "MODERATE_NOISE_ALLOWED",
  NO_NOISE_RESTRICTION = "NO_NOISE_RESTRICTION",
}

export enum CONSUMPTION_POLICY_RULE_ENUM {
    PURCHASE_REQUIRED = "PURCHASE_REQUIRED",
    OUTSIDE_PURCHASE_ALLOWED = "OUTSIDE_PURCHASE_ALLOWED",
    NO_OUTSIDE_FOOD = "NO_OUTSIDE_FOOD"
}

export enum PRIVACY_POLICY_RULE_ENUM {
    OPEN_WORKSPACE = "OPEN_WORKSPACE",
    SHARED_DESKS = "SHARED_DESKS",
    PRIVATE_ROOM = "PRIVATE_ROOM",
    OUTSIDE_PURCHASE_ALLOWED = "OUTSIDE_PURCHASE_ALLOWED",
    NO_OUTSIDE_FOOD = "NO_OUTSIDE_FOOD"
  }
